version: '3.8'
services:
  backend:
    build: ./backend
    container_name: backend_container
    ports:
      - "3500:3500"
    volumes:
      - ./backend:/backend
  frontend:
    build: ./frontend
    container_name: frontend_container
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
    stdin_open: true
    tty: true